name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: Version to be released
        required: true

permissions:
  contents: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-go@v7
        with:
          go-version: ">=1.25 <1.26"
      - uses: jdx/mise-action@v4
      - name: Build for linux/amd64
        run: mise run build --os linux --arch amd64
      - name: Create release
        run: gh release create ${{ github.event.inputs.version }} keexp-* --target ${GITHUB_REF} --title ${{ github.event.inputs.version }}
        env:
          GH_TOKEN: "${{ github.token }}"
